### ISSUE TITLE
Stacked Area Chart Not working with nvd3 version 1.8.1

### ISSUE THREAD

**Issue by stavmil** [angularjs-nvd3-directives/angularjs-nvd3-directives#365]
When running the stacked area chart example (http://angularjs-nvd3-directives.github.io/angularjs-nvd3-directives/stacked.area.chart.html) with the new version of nvd3 (1.8.1) I got the following error : 

Uncaught TypeError: nv.models.stackedAreaChart(...).width(...).height(...).margin(...).x(...).y(...).forceX(...).forceY(...).size is not a function (line 1208)

The only change to the example was the reference to nv.d3.js.

**Comment by achadee** [comment]
+1

**Comment by gregz67** [comment]
+1

**Comment by christw** [comment]
+1

**Comment by huangye177** [comment]
+1
Any update?

**Comment by ProdigyView** [comment]
What version should I be using?

**Comment by huangye177** [comment]
It seems like similar issues is also encountered by other people for a long time. Is there any update / maintenance on this issue?

**Comment by navicor90** [comment]
+1

**Comment by huangye177** [comment]
I think I have figured out the reason, I am using nvd3 1.8.1, but angularjs-nvd3-directives is actually running on 1.1.15b.

Since 1.1.15b is so old thus already not available (https://www.versioneye.com/javascript/novus:nvd3/1.1.15b), I find out 1.2.1 is working for me. 

Hope it helps.

**Comment by yppeaxy** [comment]
Are there any plans to have support for the later versions of nvd3 lib? 
1.1.15.b is pretty outdated, if not v 1.8.1 how about v 1.7 ?

**Comment by Lxrd-AJ** [comment]
+1
It also seems to be giving errors for other graph examples too, pie-charts etc nvd3 version 1.8.1

**Comment by davidcstevens** [comment]
+1
